### ISSUE TITLE
thin error and died

### ISSUE THREAD

**Issue by jaywon99** [mperham/rack-fiber_pool#16]
I used to run with ruby 1.9.2p318, thin, rack-fiber_pool-0.9.2 to serve.

but sometimes (not always), thin daemon was died with these messages

case 1

 /var/www/twitbee/shared/bundle/ruby/1.9.1/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:48:in `block (3 levels) in initialize': 
undefined method`call' for #EventMachine::Synchrony::Multi:0x00000016c5dcd8 (NoMethodError)
        from /var/www/twitbee/shared/bundle/ruby/1.9.1/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:47:in `loop'
        from /var/www/twitbee/shared/bundle/ruby/1.9.1/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:47:in`block (2 levels) in initialize'

case 2

 /var/www/twitbee/shared/bundle/ruby/1.9.1/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:48:in `block (3 levels) in initialize': undefined method`call' for #EventMachine::HttpClient:0x0000001f2cdf20 (NoMethodError)
        from /var/www/twitbee/shared/bundle/ruby/1.9.1/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:47:in `loop'
        from /var/www/twitbee/shared/bundle/ruby/1.9.1/gems/rack-fiber_pool-0.9.2/lib/fiber_pool.rb:47:in`block (2 levels) in initialize'

Do you have any idea?

**Comment by solutus** [comment]
Meet the same issue
