### ISSUE TITLE
rainbows error

### ISSUE THREAD

**Issue by fbjork** [mperham/rack-fiber_pool#7]
When I try to run my app using rainbows I get this error:

NoMethodError: undefined method `call' for nil:NilClass
    /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-3.0.3/lib/active_support/whiny_nil.rb:48:in`method_missing'
    /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rack-fiber_pool-0.9.0/lib/rack/fiber_pool.rb:17:in `block in call'
    /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rack-fiber_pool-0.9.0/lib/fiber_pool.rb:48:in`call'
    /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rack-fiber_pool-0.9.0/lib/fiber_pool.rb:48:in `block (3 levels) in initialize'
    /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rack-fiber_pool-0.9.0/lib/fiber_pool.rb:47:in`loop'
    /Users/fredrik/.rvm/gems/ruby-1.9.2-p0/gems/rack-fiber_pool-0.9.0/lib/fiber_pool.rb:47:in `block (2 levels) in initialize'
127.0.0.1 - - [22/Dec/2010 14:18:45] "GET / HTTP/1.1" 500 1538881 2.9434

any ideas what's going on?

**Comment by maxjustus** [comment]
I get the same error :(

**Comment by jmonster** [comment]
ditto.

**Comment by betamatt** [comment]
This happens when Rainbows isn't configured to use EventMachine as its backend.

Rainbows! do
  use :EventMachine
end
